---
title: "線型モデルのお勉強ノート"
author: "yoshi"
date: '2016-09-13'
output:
  html_document:
    number_section: yes
    smart: yes
    toc: yes
    toc_depth: 2
abstract: みんなのR、16章のお勉強。
---
```{r, message=FALSE, warning=FALSE}
require(UsingR)
require(ggplot2)
require(tidyr)
require(dplyr)
require(plotly)
```
# 単回帰

```{r}
data("father.son")
head(father.son)
ggplot(father.son , aes(x = fheight , y = sheight)) + geom_point() +
   stat_smooth(method = "lm") + labs(x = "Fathers" , y = "sons")
```

```{r}
heightsLM <- lm(sheight ~ fheight , data = father.son)
heightsLM
```
結果の詳細を見るには`summary()`を使う。
```{r}
summary(heightsLM)
```
# 重回帰
```{r}
housing <- read.table ("http://www.jaredlander.com/data/housing.csv",
   sep = ",", header = TRUE,
   stringsAsFactors = FALSE)
```
```{r}
names(housing) <- c("Neighborhood" , "Class" , "Units" , "YearBuilt" ,
    "SqFt" , "Income" , "IncomeperSqFt" , "Expence" ,
    "ExpencePerSqFt" , "NetIncome" , "Value" ,
    "ValueperSqFt" , "Boro")
housing <- housing[housing$Units < 1000 ,] # 外れ値を除く
head(housing)
```

```{r}
house1 <- lm(ValueperSqFt ~ Units + SqFt + Boro , data = housing)
summary(house1)
```
```{r}
require(coefplot)
coefplot(house1)
```
相互作用も入れられる。次の式は$y=a(x_1 + x_2)^2 + b + \epsilon$で回帰する。`I()`を使わないとフォーミュラ式は$y=a x_1 + b x_2 + c x_1 * x_2 + d + \epsilon$と解釈してしまう。
```{r}
house9 <- lm(ValueperSqFt ~ I(Units + SqFt)^2 , data = housing)
coefplot(house9)
```

# 汎化誤差  
```{r}
noise <- 0.2
x.train <- seq(1, 2*pi, length.out = 10)
y.train <- sin(x.train) + rnorm(length(x.train), mean = 0, sd = noise)
x.test <- seq(1, 2*pi, length.out = 10)
y.test <- sin(x.train) + rnorm(length(x.train), mean = 0, sd = noise)
model.1 <- lm(formula = y.train ~ x.train)
df <- data.frame(x=x.train, y.train=y.train, y.test=y.test)
ggplot(df, aes(x=x.train)) + geom_point(aes(y=y.train, shape='train')) + geom_point(aes(y=y.test, shape='test')) + 
  geom_smooth(method='lm', aes(x=x.train, y=y.train), se=F)
```
```{r}
ggplot(df, aes(x=x.train)) + geom_point(aes(y=y.train, shape='train')) + geom_point(aes(y=y.test, shape='test')) + 
  geom_smooth(method='lm', formula = 'y~I(x^2)+x',aes(x=x.train, y=y.train), se=F)
```
```{r}
ggplot(df, aes(x=x.train)) + geom_point(aes(y=y.train, shape='train')) + geom_point(aes(y=y.test, shape='test')) + 
  geom_smooth(method='lm', formula='y~I(x^3) + I(x^2) + x', aes(x=x.train, y=y.train), se=F)
```

```{r}
rmse.train <- c()
rmse.test <- c()
for (deg in 1:9) {
  model <- lm(formula = y.train~poly(x.train,deg))
  rmse <- sqrt( sum( ( y.train - predict(model) )^2 ) / length(x.train) )
  rmse.train <- c(rmse.train,rmse)
  rmse <- sqrt( sum( ( y.test - predict(model) )^2 ) / length(x.train) )
  rmse.test <- c(rmse.test,rmse)
}
df <- data.frame(degree =rep(1:9,2), rmseError=c(rmse.train, rmse.test), data=c(rep('train',9), rep('test',9)))
ggplot(df,  aes(x=degree, y=rmseError, group=data, color=data)) + geom_point()
```
汎化誤差が最小になるのは三次のモデルである。
