---
title: "時系列データ"
author: "yoshi"
date: '2016-09-21'
output:
  html_document:
    number_section: yes
    smart: yes
    toc: yes
    toc_depth: 2
abstract: みんなのR 21章の勉強ノート
---
# ARIMA
```{r}
require(WDI)
# データを取得する
gdp <- WDI(country = c("US" , "CA" , "GB" , "DE" , "CN" , "JP" , "SG" , "IL") ,
indicator = c("NY.GDP.PCAP.CD" , "NY.GDP.MKTP.CD") ,
start = 1960 , end = 2011)
# 変数名を変更する
names(gdp) <- c("iso2c" , "country" , "Year" , "PerCapGDP" , "GDP")
```

```{r}
head(gdp)
```

```{r}
require(ggplot2)
require(scales)
# 1人あたりのGDP
ggplot(gdp , aes(Year , PerCapGDP , color = country , linetype = country)) +
geom_line() + scale_y_continuous(label = dollar)
require(useful)
```

```{r}
us <- gdp$PerCapGDP[gdp$country == "United States"]
# 時系列データへ変換
us <- ts(us , start = min(gdp$Year) , end = max(gdp$Year))
plot(us)
```

自己共分散関数（ACF）と偏自己共分散関数（PACF）を見る。
```{r}
acf(us)
```

```{r}
pacf(us)
```
原系列はトレンドを持っているので差分系列を考える。ndiffs()で適切な回数差分を取ってくれる。
```{r}
require(forecast)
ndiffs(us)
```
ARIMAでフィットする。最適なパラメータは勝手に計算してくれる。
```{r}
usBest <- auto.arima(x = us)
usBest
```
  
```{r}
theForecast <- forecast(object = usBest , h = 5)
plot(theForecast)
```

# GARCH
```{r}
require(quantmod)
att <- getSymbols("T" , auto.assign = FALSE)
```
```{r}
chartSeries(att)
```

```{r}
require(rugarch)
attSpec <- ugarchspec(variance.model = list(model = "sGARCH" ,
garchOrder = c(1,1)) ,
mean.model = list(armaOrder = c(1,1)) ,
distribution.model = "std")
```
```{r}
attClose <- att$T.Close
attGarch <- ugarchfit (spec = attSpec , data = attClose)
```

