---
title: "部分空間法のお勉強"
author: "yoshi"
date: '2016-12-21'
output:
  html_document:
    number_section: yes
    smart: yes
    toc: yes
    toc_depth: 2
abstract: はじパタ第九章
---
```{r}
# Load the MNIST digit recognition dataset into R
# http://yann.lecun.com/exdb/mnist/
# assume you have all 4 files and gunzip'd them
# creates train$n, train$x, train$y  and test$n, test$x, test$y
# e.g. train$x is a 60000 x 784 matrix, each row is one digit (28x28)
# call:  show_digit(train$x[5,])   to see a digit.
# brendan o'connor - gist.github.com/39760 - anyall.org

load_mnist <- function() {
  load_image_file <- function(filename) {
    ret = list()
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    ret$n = readBin(f,'integer',n=1,size=4,endian='big')
    nrow = readBin(f,'integer',n=1,size=4,endian='big')
    ncol = readBin(f,'integer',n=1,size=4,endian='big')
    x = readBin(f,'integer',n=ret$n*nrow*ncol,size=1,signed=F)
    ret$x = matrix(x, ncol=nrow*ncol, byrow=T)
    close(f)
    ret
  }
  load_label_file <- function(filename) {
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    n = readBin(f,'integer',n=1,size=4,endian='big')
    y = readBin(f,'integer',n=n,size=1,signed=F)
    close(f)
    y
  }
  train <<- load_image_file('data/mnist/train-images-idx3-ubyte')
  test <<- load_image_file('data/mnist/t10k-images-idx3-ubyte')
  
  train$y <<- load_label_file('data/mnist/train-labels-idx1-ubyte')
  test$y <<- load_label_file('data/mnist/t10k-labels-idx1-ubyte')  
}


show_digit <- function(arr784, col=gray(12:1/12), ...) {
  image(matrix(arr784, nrow=28)[,28:1], col=col, ...)
}
```
```{r}
require(ggplot2)
require(tidyr)
require(dplyr)
```
```{r}
show_digit(train$x[6,])
```
# 直交基底のプロット
```{r}
train.x.small <- train$x[train$y==4,]
train.x.small <- train.x.small[1:10,]
qrModel <- qr(train.x.small)
R.train.small <- qr.R(qrModel)
par(mfrow=c(2,5))
for (i in 1:10){
  show_digit(R.train.small[i,])
}
```
# 主成分分析  
```{r}
X<- train$x
X <- X[train$y==4,]
Xbar <- X - apply(X,1,mean)
S <- t(Xbar) %*% Xbar
USV <- svd(S)
U <- USV$u
V <- USV$v
S <- diag(USV$d)
```
## 主成分ベクトル
```{r}
par(mfrow=c(2,5))
for (i in 1:10){
  show_digit(U[,i])
}
```
## ベクトル量子化  
```{r}
par(mfrow=c(2,5))
v <- matrix( Xbar[1,] )
v.orig <- v
pca.comp <- data.frame()
for (i in 1:10){
  s <- t(v.orig) %*% matrix(U[,i])
  v <- v + s[1,1] * matrix(U[,i])
  show_digit(v)
  pca.comp[i,1] <- s
}
```
```{r}
for (i in 1:100){
  s <- t(v.orig) %*% matrix(U[,i])
  v <- v + s[1,1] * matrix(U[,i])
  pca.comp[i,1] <- s
  pca.comp[i,2] <- i
}
names(pca.comp) <- c('Projection_Component', 'Principal_Component')
ggplot(pca.comp) + geom_bar(aes(x=Principal_Component, y=Projection_Component), stat="identity")
```

